# Generated by Django 4.1.7 on 2023-05-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='descriptions',
            new_name='description',
        ),
    ]
